# Black Duck on GitHub-hosted ephemeral runner
name: blackduck

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest

    env:
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      PROJECT: strool-apache-roller
      BRANCH: ${GITHUB_REF##*/}
      DETECT_DIAGNOSTICS: TRUE

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Detect Rapid Scan Action
      uses: synopsys-sig/detect-action@v0.3.2
      with:
          scan-mode: INTELLIGENT # Can be omitted, since this is the default value
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          
