# Black Duck on GitHub-hosted ephemeral runner
name: blackduck

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  blackduck:
    runs-on: ubuntu-latest

    env:
      BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
      BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
      PROJECT: strool-apache-roller
      BRANCH: ${GITHUB_REF##*/}
      DETECT_DIAGNOSTICS: TRUE

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
        
    - name: Detect Rapid Scan Action
      uses: synopsys-sig/detect-action@v0.3.2
      with:
        args: --detect.project.name=$PROJECT --detect.project.version.name=$BRANCH --detect.excluded.detector.types=GRADLE
